export const REQUEST_USER_LIST = "REQUEST_USER_LIST";
export const SUCCESS_USER_LIST = "SUCCESS_USER_LIST";
export const USER_LIST_ERROR = "USER_LIST_ERROR";
export const REMOVE_USER = "REMOVE_USER";
export const REQUEST_USER_INFO = "REQUEST_USER_INFO";
export const SUCCESS_USER_INFO = "SUCCESS_USER_INFO";
export const USER_INFO_ERROR = "USER_INFO_ERROR";